# Generated by Django 3.1.2 on 2021-01-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='engine',
            field=models.CharField(choices=[('benzin', 'benzin'), ('diesel', 'diesel'), ('električni', 'električni'), ('hibrid', 'hibrid')], max_length=20),
        ),
    ]
